### ISSUE TITLE
Issue/Bug with scroll

### ISSUE THREAD

**Issue by m-bagheri** [hxf31891/react-gradient-color-picker#2]
Dear @hxf31891 

I wanted to thank you for developing this great colour picker.
I've found a bug in the picker which occurs when you scroll the page/parent wrapper of the colour picker.
If there is any scroll in the page and scroll is occurred and position of the colour picker is changed on the page, the picker stops putting the pointer in the correct position and gets stuck at the top.

I found that if you add something like the following to the index.js it would solve the issue.
I have done this just for the whole window scroll and I believe this needs to be changed to be applied to every parent element of the picker.

`const onScroll = () => {
    return setBounds(contRef?.current?.getBoundingClientRect());
  };
  window.addEventListener('scroll', onScroll, {once: true});`

Could you please fix this issue and release a new update on NPM so I can grab the latest version and use it?

Thank you very much in advance.

**Comment by m-bagheri** [comment]
To help you, I added a pull request to make it work. I've explained in the pull request what I've done.

**Comment by hxf31891** [comment]
@m-bagheri thank you for pointing this out and for suggested fix!

I’ve got a minute to look this over now and hopefully will have a new version up tonight.

**Comment by m-bagheri** [comment]
Thanks @hxf31891 

I did try to do it smarter using the `useEffect` and setting the top and left offset changes but it doesn't work properly and the first click fails but the second click works. So there is a lag if we use `useEffect`.
That's why I did it with pure JavaScript and based on all parent elements scroll.

If you have a better solution I would love to know how it can be done and I'm happy to help.

Thanks @hxf31891 
Much appreciated

**Comment by hxf31891** [comment]
This is an interesting one, now that I am looking back at the code I remember that I addressed a similar bug on window resize at src/index.js 13. 

I wonder if we can track scroll position with a state variable and simply add it to the same useEffects dependencies.

**Comment by hxf31891** [comment]
I believe this bug is fixed with [e448ae4](https://github.com/hxf31891/react-gradient-color-picker/commit/e448ae460ccdb115020499a8c1b009a90687f182). Please confirm when you get a chance.

**Comment by m-bagheri** [comment]
Hi @hxf31891 

Thank you very much for releasing this update so quickly. I just tested your release and even though it works fine on window scroll but it still fails if you have the colour picker inside a div/wrapper which has it's own scroll (css being overflow: scroll). That's why I did that code to go through all the parent elements of the colour picker and if there is any scroll on any of them, then update the picker boundries.

I'm not sure if you are able to do that or not but the other solution might be to pass `bounds` variable in `index.js` here
`function ColorPicker({ value = 'rgba(175, 51, 242, 1)', onChange = () => {}, hideControls, hideInputs, hidePresets, presets }) {`
which would then let everyone to do their own coding for boundaries.

Currently I've fixed the issue my end by applying a hack and when an inside div is scrolled to trigger window scroll up 1 px and window scroll down 1 px to make it trigger the boundaries update as it's just updated through whole window scroll.

Thanks @hxf31891 for the great work you've done and being so quick :)

**Comment by m-bagheri** [comment]
Also I found another bug which relates to sliders for colour points and opacity.
None of them are draggable and you cannot drag them. As soon as you start dragging them it stops. This makes using the picker very difficult especially with multiple colour points in the first slider. You need to keep add and removing due to dragging not working.
I've attache a screenshot of the points that I'm referring to.
I hope this makes sense and let me know if I can help.

Thanks @hxf31891 

![Screenshot 2022-04-04 at 15 13 36](https://user-images.githubusercontent.com/4902792/161483573-30db1bc0-fa81-42eb-bc45-0ac839febe6a.png)

**Comment by hxf31891** [comment]
I noticed this one the other day as well, in the process of implementing a fix.

Will keep you updated.

**Comment by hxf31891** [comment]
@m-bagheri I just pushed up a new version (1.4.5) that addresses the issue you raised and a few other little bugs I've been meaning to take care of.

I also updated the control UI a bit.

Would appreciate any feedback!

**Comment by hxf31891** [comment]
I also believe I fixed the scroll/resize issue once and for all by eliminating the bounds and instead passing in the location from the event.

**Comment by m-bagheri** [comment]
@hxf31891 
Awesome work. Well done. This is looking perfect and working great. Thanks @hxf31891 for the great work you did
Just noticed the layout is also changed and it looks so much slicker and I love the new look. well done. I just noticed there is 3 dots on the right hand side which I thought it should open up a menu or something but it doesn't do anything. Is it meant to do something? Why is it there for please?

I've attached a screenshot of what I'm referring to.

Thanks @hxf31891 and well done :)
![Screenshot 2022-04-08 at 08 58 46](https://user-images.githubusercontent.com/4902792/162339879-b1256c1d-e33f-4117-b6c4-f67b0c18d919.png)

**Comment by hxf31891** [comment]
Whoops, thats part of a 'options' feature I'm working on. It wasn't supposed to go live yet, pulling that out now.

Glad you are liking the picker and appreciate the feedback, let me know if you find anymore issues or have any thoughts or requests.

**Comment by hxf31891** [comment]
@m-bagheri new version without button is live.

**Comment by m-bagheri** [comment]
Awesome
Thanks @hxf31891 
Looking great
I will keep you posted if I find any other issue :)
